# Generated by Django 4.1.1 on 2022-10-03 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("note_api", "0002_alter_profile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="note_api.profile",
            ),
            preserve_default=False,
        ),
    ]
